create table users (
  user_id int generated by default as identity not null primary key,
  first_name character varying(256) not null,
  last_name character varying(256),
  phone_number character varying(13) not null,
  user_role int not null default 1,
  age smallint,
  is_male boolean,
  created_at timestamp with time zone  not null default current_timestamp
);

create table user_sessions (
  session_id int generated by default as identity not null primary key,
  user_id int references users (user_id) not null,
  token_id character varying(36) not null,
  is_logged_out boolean not null default false,
  logged_in_at timestamp with time zone not null default current_timestamp,
  logged_out_at timestamp with time zone,
  remote_ip inet not null, 
  device text not null
);

create table code_sessions (
  code_id int generated by default as identity not null primary key,
  code int not null,
  phone_number character varying(13) not null,
  attempts smallint default 0,
  created_at timestamp with time zone not null default current_timestamp
);

create table languages (
  language_id int generated by default as identity not null primary key,
  lang_name varchar(64) not null,
  lang_short_name varchar(2) not null,
  created_at timestamp with time zone not null default current_timestamp
);

create table authors (
  author_id int generated by default as identity not null primary key,
  first_name character varying(256) not null,
  last_name character varying(256),
  language_id int references languages (language_id) not null,
  created_at timestamp with time zone not null default current_timestamp
);

create table readers (
  reader_id int generated by default as identity not null primary key,
  first_name character varying(256) not null,
  last_name character varying(256),
  language_id int references languages (language_id) not null,
  created_at timestamp with time zone not null default current_timestamp
);

create table publishers (
  publisher_id int generated by default as identity not null primary key,
  publisher_name character varying(256) not null,
  created_at timestamp with time zone not null default current_timestamp
);

create table genres (
  genre_id int generated by default as identity not null primary key,
  genre_name character varying(256) not null,
  created_at timestamp with time zone not null default current_timestamp
);

create table age_intervals (
  agi_id int generated by default as identity not null primary key,
  agi_name character varying(128) not null,
  created_at timestamp with time zone not null default current_timestamp
);

create table price_types (
  pricet_id int generated by default as identity not null primary key,
  pricet_name character varying(128) not null,
  created_at timestamp with time zone not null default current_timestamp
);

create table books (
  book_id int generated by default as identity not null primary key,
  book_name varchar(1024) not null,
  book_desc text not null,
  price decimal(10,2) not null,
  reader_id int references readers (reader_id) not null,
  pricet_id int references price_types (pricet_id) not null,
  author_id int references authors (author_id) not null,
  publisher_id int references publishers (publisher_id) not null,
  agi_id int references age_intervals (agi_id) not null,
  genre_id int references genres (genre_id) not null,
  created_at timestamp with time zone not null default current_timestamp
);

create table book_tags (
  tag_id int generated by default as identity not null primary key,
  book_id int references books (book_id) not null,
  tag_name character varying(1024) not null,
  created_at timestamp with time zone not null default current_timestamp
);

create table book_chapters (
  chapter_id int generated by default as identity not null primary key,
  chapter_order smallint not null,
  chapter_name text not null,
  audio_id int references audios (audio_id) not null,
  book_id int references books (book_id) not null,
  created_at timestamp with time zone not null default current_timestamp
);

create table audios (
  audio_id int generated by default as identity not null primary key,
  audio_duration time not null,
  audio_type character varying(8) not null,
  audio_src character varying(36) not null,
  created_at timestamp with time zone not null default current_timestamp
);

create table bookmarks (
  bookmark_id int generated by default as identity not null primary key,
  book_id int references books (book_id) not null,
  user_id int references users (user_id) not null,
  created_at timestamp with time zone not null default current_timestamp
);

create table orders (
  order_id int generated by default as identity not null primary key,
  book_id int references books (book_id) not null,
  is_completed boolean not null default false,
  created_at timestamp with time zone not null default current_timestamp
);

create table providers (
  prodiver_id int generated by default as identity not null primary key,
  prodiver_name character varying(512) not null,
  redirect_url text not null,
  token text not null,
  created_at timestamp with time zone not null default current_timestamp
);